"""Markdown report generation and persistence."""

import os
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any
from .models import Finding, Evidence


def generate_report_md(
    findings: List[Finding],
    evidence: Evidence,
    severity: str,
    risk_score: float,
    decision: str,
    override_reason: str | None = None,
    history_hint: Dict[str, Any] | None = None,
    weak_stack_touched: List[str] | None = None,
    quick_fixes: List[str] | None = None,
    learning_points: List[Dict[str, Any]] | None = None,
) -> str:
    """
    Generate a markdown report.

    Args:
        findings: List of findings
        evidence: Research evidence
        severity: Overall severity
        risk_score: Overall risk score (0-1)
        decision: allow/block/override
        override_reason: Reason for override (if applicable)
        history_hint: History scan results
        weak_stack_touched: Weak stacks that were touched
        quick_fixes: Quick fix suggestions

    Returns:
        Markdown report as string
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    md_lines = [
        "# 🛡️ PushGuardian Report\n",
        f"**Generated:** {timestamp}\n",
        f"**Decision:** `{decision.upper()}`\n",
        f"**Severity:** `{severity.upper()}`\n",
        f"**Risk Score:** {risk_score:.2f}/1.00\n",
        "",
    ]

    # Override reason
    if override_reason:
        md_lines.extend(
            [
                "## ⚠️ Override Applied\n",
                f"{override_reason}\n",
                "",
            ]
        )

    # Findings summary
    if findings:
        md_lines.append("## 🔍 Findings\n")
        for i, finding in enumerate(findings, 1):
            md_lines.extend(
                [
                    f"### {i}. [{finding.severity.upper()}] {finding.title}\n",
                    f"**Type:** `{finding.kind}`  ",
                    f"**Confidence:** {finding.confidence:.0%}\n",
                    f"{finding.detail}\n",
                    f"**Fix Now:**\n```\n{finding.fix_now}\n```\n",
                    "",
                ]
            )
    else:
        md_lines.append("## ✅ No Critical Findings\n\n")

    # Quick fixes
    if quick_fixes:
        md_lines.append("## 🔧 Quick Action Items\n")
        for fix in quick_fixes:
            md_lines.append(f"- {fix}")
        md_lines.append("\n")

    # Security Evidence (only if there are findings)
    if findings and evidence.principle_links:
        md_lines.append("## 🔒 Security Resources\n")
        md_lines.append("Reference materials for the security issues found:\n\n")
        for link in evidence.principle_links[:4]:  # Max 4 security links
            md_lines.append(f"- {link}\n")
        md_lines.append("\n")

    # Learning Section (only for weak stacks)
    if weak_stack_touched and learning_points:
        md_lines.append("---\n\n")
        md_lines.extend(
            [
                "## 📖 Learning: Weak Stack Detected\n",
                f"⚠️ This change touches **{', '.join(weak_stack_touched)}** which you're less familiar with.\n\n",
                "### 🎯 Fundamental Concepts in Your Code\n",
            ]
        )

        for lp in learning_points:
            # Learning points always use 🟡 to distinguish from security findings
            md_lines.extend(
                [
                    f"🟡 **{lp.get('concept', 'Unknown')}**\n",
                    f"   {lp.get('detail', 'No details available')}\n\n",
                ]
            )

        # Learning resources (tutorials only)
        if evidence.example_links:
            md_lines.append("### 💡 Tutorials & Examples\n")
            for link in evidence.example_links[:5]:
                md_lines.append(f"- {link}\n")
            md_lines.append("\n")

    # History hint
    if history_hint:
        md_lines.append("## 📅 History Scan\n")
        if history_hint.get("first_seen_commit"):
            md_lines.append(f"First seen in commit: `{history_hint['first_seen_commit']}`\n")
        md_lines.append(f"{history_hint.get('message', 'No history available')}\n\n")

    # Footer
    md_lines.extend(
        [
            "---\n",
            "*Generated by [PushGuardian](https://github.com/parksihyun87/pushguardian)*\n",
        ]
    )

    return "".join(md_lines)


def save_report(
    report_md: str,
    report_dir: str,
    prefix: str = "report",
) -> str:
    """
    Save report to markdown file.

    Args:
        report_md: Markdown content
        report_dir: Directory to save report
        prefix: Filename prefix

    Returns:
        Path to saved report
    """
    # Create directory if needed
    report_path = Path(report_dir)
    report_path.mkdir(parents=True, exist_ok=True)

    # Generate filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{prefix}_{timestamp}.md"
    filepath = report_path / filename

    # Write file
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report_md)

    return str(filepath)
